/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 enigma.gltf --transform
Author: Science Museum Group (https://sketchfab.com/sciencemuseum)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/enigma-machine-1934-c8ee76c383654e3095ea4cc9e7990274
Title: Enigma machine, 1934
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/enigma-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[0, -3.49, 4.95]} rotation={[-Math.PI, 0, 0]}>
        <group position={[-9.89, -21.71, -16.98]}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={
              materials['enigma-machine-750-EDIT-final-textured_Material_u1_v1']
            }
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={
              materials['enigma-machine-750-EDIT-final-textured_Material_u1_v1']
            }
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={
              materials['enigma-machine-750-EDIT-final-textured_Material_u1_v1']
            }
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={
              materials['enigma-machine-750-EDIT-final-textured_Material_u1_v1']
            }
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={
              materials['enigma-machine-750-EDIT-final-textured_Material_u1_v1']
            }
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={
              materials[
                'enigma-machine-750-EDIT-final-textured_Material_u1_v1_NONE'
              ]
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/enigma-transformed.glb');
