/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mac.gltf --transform
Author: Armen Gevorgyan (https://sketchfab.com/armeniouz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-low-poligonal-free-download-5d2c9be39d294d4a8fc702ac04cf3444
Title: Macbook low poligonal - free download
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mac-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane001_Standard_5_0.geometry}
        material={materials.Standard_5}
        position={[-0.11, 0.27, 2.61]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Plane002_Standard_5_0.geometry}
        material={materials.Standard_5}
        position={[0.09, 9.64, -12.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder001_Standard_5_0.geometry}
        material={materials.Standard_5}
        position={[-11.93, -0.05, -4.9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Box001_Standard_5_0.geometry}
        material={materials.Standard_5}
        position={[0, 0.27, -7.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder002_Standard_5_0.geometry}
        material={materials.Standard_5}
        position={[11.97, -0.05, -4.9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder003_Standard_5_0.geometry}
        material={materials.Standard_5}
        position={[-11.93, -0.05, 10.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder004_Standard_5_0.geometry}
        material={materials.Standard_5}
        position={[11.97, -0.05, 10.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.screen_screen_0.geometry}
        material={materials.screen}
        position={[0, 0.49, -7.1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload('/mac-transformed.glb');
