/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoe.gltf --transform
Author: GoMeasure3D (https://sketchfab.com/gomeasure3d)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/shoe-3d-scan-f3814a3896dc4a97829b36f2443ef12a
Title: Shoe 3D Scan
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[0.67, 820.13, 579.66]} rotation={[2.84, 0, -0.01]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/shoe-transformed.glb');
